name: Delete gh-pages
on:
  delete:
    branches-ignore: ["gh-pages"]
jobs:
  Delete_snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Git init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          TARGET_PATH: captures
        run: |
          BRANCH=`cat $GITHUB_EVENT_PATH | jq -r ".ref" | sed -e 's/\//-/g'`
          mkdir -p __gh-pages__/${TARGET_PATH}
          cd __gh-pages__
          git init
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email ${GITHUB_ACTOR}@git
          git config core.sparsecheckout true
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          echo /${TARGET_PATH}/${BRANCH} > .git/info/sparse-checkout
          echo /${TARGET_PATH}/index.txt >> .git/info/sparse-checkout
          git pull origin gh-pages || true
          git checkout -b gh-pages
      - name: Delete gh-pages
        env:
          TARGET_PATH: captures
        working-directory: ./__gh-pages__
        run: |
          BRANCH=`cat $GITHUB_EVENT_PATH | jq -r ".ref" | sed -e 's/\//-/g'`
          rm -rf ${TARGET_PATH}/${BRANCH} || true
          git ls-files | sed -r "s/^${TARGET_PATH}\/([^\/]+)\/.*/\1/;t;d" | sed /^${BRANCH}$/d | sort -u > ${TARGET_PATH}/index.txt
      - name: Save gh-pages
        env:
          TARGET_PATH: captures
        working-directory: ./__gh-pages__
        run: |
          BRANCH=`cat $GITHUB_EVENT_PATH | jq -r ".ref" | sed -e 's/\//-/g'`
          for i in `seq 2` ; do
            git add .
            git commit -m "delete ${BRANCH}" || true
            (git push origin gh-pages && break) || 
              (git pull origin gh-pages && git push origin gh-pages && break) || 
              (git ls-files | sed -r "s/^${TARGET_PATH}\/([^\/]+)\/.*/\1/;t;d" | sed /^${BRANCH}$/d | sort -u > ${TARGET_PATH}/index.txt)
          done
