name: Pull request
on:
  pull_request:
jobs:
  Create_pull_snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules(yarn.lock)
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.OS }}-build-${{ env.cache-name }}
      - name: Package install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Pull Target Shapshot
        if: ${{github.ref != 'refs/heads/master'}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WORK_DIR: temp
          TARGET_PATH: captures
          SRC_PATH: __screenshots__
        run: |
          BRANCH=`echo ${GITHUB_BASE_REF} | sed -e 's/\//-/g'`         
          mkdir -p ${WORK_DIR}/${TARGET_PATH}/${BRANCH}
          cd ${WORK_DIR}
          git init
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email ${GITHUB_ACTOR}@git
          git config core.sparsecheckout true
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          echo /${TARGET_PATH}/${BRANCH} > .git/info/sparse-checkout    
          git pull origin gh-pages || true
          git checkout -b gh-pages   
          mv -f ${TARGET_PATH}/${BRANCH}/${SRC_PATH} .. || true
      - name: Storybook
        run: yarn storybook:build
      - name: Screenshot
        if: ${{github.ref != 'refs/heads/master'}}
        run: |
          yarn test:screenshot
          yarn reg-cli __screenshots__ screenshots __image_diff__ -J __image_diff__/index.json
      - name: Git init
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TARGET_PATH: captures
        run: |
          TARGET=`echo ${GITHUB_BASE_REF} | sed -e 's/\//-/g'`  
          BRANCH=`echo ${GITHUB_HEAD_REF} | sed -e 's/\//-/g'`
          BRANCH=${BRANCH}--${TARGET}
          mkdir __gh-pages__
          cd __gh-pages__
          git init
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email ${GITHUB_ACTOR}@git
          git config core.sparsecheckout true
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          echo /${TARGET_PATH}/index.txt > .git/info/sparse-checkout
          echo /${TARGET_PATH}/${BRANCH} >> .git/info/sparse-checkout
          git pull origin gh-pages || true
          git checkout -b gh-pages
      - name: Create gh-pages
        env:
          TARGET_PATH: captures
          SRC_PATH1: storybook-static
          SRC_PATH2: __screenshots__
          SRC_PATH3: __image_diff__
        working-directory: ./__gh-pages__
        run: |
          TARGET=`echo ${GITHUB_BASE_REF} | sed -e 's/\//-/g'`  
          BRANCH=`echo ${GITHUB_HEAD_REF} | sed -e 's/\//-/g'`
          BRANCH=${BRANCH}--${TARGET}
          rm -rf ${TARGET_PATH}/${BRANCH} || true
          mkdir -p ${TARGET_PATH}/${BRANCH}
          mv ../${SRC_PATH1} ${TARGET_PATH}/${BRANCH}/stories
          mv ../${SRC_PATH2} ${TARGET_PATH}/${BRANCH}/`echo ${SRC_PATH2} | sed -r "s/__(.*)__/\1/"` || true
          mv ../${SRC_PATH3} ${TARGET_PATH}/${BRANCH}/`echo ${SRC_PATH3} | sed -r "s/__(.*)__/\1/"` || true
          git ls-files | sed -r "s/^${TARGET_PATH}\/([^\/]+)\/.*/\1/;t;d" | echo -e "`cat`\n${BRANCH}" | sort -u > ${TARGET_PATH}/index.txt
      - name: Save gh-pages
        working-directory: ./__gh-pages__
        run: |
          TARGET=`echo ${GITHUB_BASE_REF} | sed -e 's/\//-/g'`  
          BRANCH=`echo ${GITHUB_HEAD_REF} | sed -e 's/\//-/g'`
          BRANCH=${BRANCH}--${TARGET}
          git add .
          git commit -m "Create Snapshot($BRANCH)" || true
          for i in `seq 5` ; do
            (git push origin gh-pages && break) || sleep 5
          done
      - name: Write comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: node .github/workflows/scripts/comment.js
      # - name: Setup tmate session
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      #   uses: mxschmitt/action-tmate@v3
